name: build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: m21
          - device: m31
    name: "🚧 Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1
          
      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev -y
          bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/b170134a94dac3594df506716bc7b802add2724b/setup.sh)
          
      - name: Run build
        run: |
          
          DEVICE=${{matrix.device}} ./auto_workflow_clang.sh

      - name: Device Name & Config
        run: |
          cat .config | grep CONFIG_LOCALVERSION=
          echo ''
          echo ''
          echo ''
          cat .config

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: N_kernel_NEUTRON-Clang_18
          path: AIK/N_KERNEL.*.zip
