name: build

on:

  workflow_dispatch:
    inputs:
      DEVICE_BLD:
        description: 'DEVICE_BLD (The device you want to build for m21 or m31)'
        required: true
        default: 'm21'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 1
          
      - name: Setup Toolchains
        run: |
          bash init_clang_12.sh
          
      - name: Run build
        run: |
          export PATH=$PWD/toolchain/proton-clang/bin:$PATH
          DEVICE=${{ github.event.inputs.DEVICE_BLD }} ./auto_workflow_clang.sh

      - name: Device Name & Config
        run: |
          cat .config | grep CONFIG_LOCALVERSION=
          echo ''
          echo ''
          echo ''
          cat .config

      - name: Upload kernel
        uses: actions/upload-artifact@v3.1.2
        with:
          name: N_kernel_Proton-Clang_13
          path: AIK/N_KERNEL.*.zip